/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register a new user and initial organization */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RegisterRequest"];
                };
            };
            responses: {
                /** @description User and organization created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RegisterResponse"];
                    };
                };
                400: components["responses"]["BadRequest"];
                409: components["responses"]["Conflict"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Authenticate and create a session */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                /** @description Session token returned */
                200: {
                    headers: {
                        /** @description HTTP-only `ruckchat_session` cookie valid for 30 days */
                        "Set-Cookie"?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LoginResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Invalidate the current session */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Session invalidated */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the authenticated user's profile */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description User profile */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UserResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update the authenticated user's profile */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateProfileRequest"];
                };
            };
            responses: {
                /** @description Updated profile */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UserResponse"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
            };
        };
        trace?: never;
    };
    "/organizations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List organizations for the authenticated user */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of organizations */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OrganizationList"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        /** Create a new organization */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateOrganizationRequest"];
                };
            };
            responses: {
                /** @description Organization created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Organization"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                409: components["responses"]["Conflict"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organizations/{organization_id}/members": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organization_id: components["schemas"]["Uuid"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Invite a user to the organization */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    organization_id: components["schemas"]["Uuid"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["InviteMemberRequest"];
                };
            };
            responses: {
                /** @description Member invited */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OrganizationMembership"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                409: components["responses"]["Conflict"];
            };
        };
        /** Remove a member from the organization */
        delete: {
            parameters: {
                query: {
                    user_id: components["schemas"]["Uuid"];
                };
                header?: never;
                path: {
                    organization_id: components["schemas"]["Uuid"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Member removed */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        options?: never;
        head?: never;
        /** Change a member's role in the organization */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    organization_id: components["schemas"]["Uuid"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ChangeRoleRequest"];
                };
            };
            responses: {
                /** @description Role updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        trace?: never;
    };
    "/organizations/{organization_id}/channels": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organization_id: components["schemas"]["Uuid"];
            };
            cookie?: never;
        };
        /** List channels visible to the user */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    organization_id: components["schemas"]["Uuid"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of channels */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ChannelList"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
            };
        };
        put?: never;
        /** Create a channel */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    organization_id: components["schemas"]["Uuid"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateChannelRequest"];
                };
            };
            responses: {
                /** @description Channel created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Channel"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                409: components["responses"]["Conflict"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/channels/{channel_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                channel_id: components["schemas"]["Uuid"];
            };
            cookie?: never;
        };
        /** Get a channel */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    channel_id: components["schemas"]["Uuid"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Channel details */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Channel"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        /** Archive a channel */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    channel_id: components["schemas"]["Uuid"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Channel archived */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Channel"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                409: components["responses"]["Conflict"];
            };
        };
        options?: never;
        head?: never;
        /** Update channel topic and purpose */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    channel_id: components["schemas"]["Uuid"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateChannelRequest"];
                };
            };
            responses: {
                /** @description Channel updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Channel"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        trace?: never;
    };
    "/channels/{channel_id}/members": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                channel_id: components["schemas"]["Uuid"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add a member to a channel */
        post: {
            parameters: {
                query: {
                    user_id: components["schemas"]["Uuid"];
                };
                header?: never;
                path: {
                    channel_id: components["schemas"]["Uuid"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Member added */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ChannelMembership"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                409: components["responses"]["Conflict"];
            };
        };
        /** Remove a member from a channel */
        delete: {
            parameters: {
                query: {
                    user_id: components["schemas"]["Uuid"];
                };
                header?: never;
                path: {
                    channel_id: components["schemas"]["Uuid"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Member removed */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/channels/{channel_id}/messages": {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                channel_id: components["schemas"]["Uuid"];
            };
            cookie?: never;
        };
        /** Get message history for a channel */
        get: {
            parameters: {
                query?: {
                    limit?: number;
                    offset?: number;
                };
                header?: never;
                path: {
                    channel_id: components["schemas"]["Uuid"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of messages */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MessageList"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        /** Post a message to a channel */
        post: {
            parameters: {
                query?: {
                    limit?: number;
                    offset?: number;
                };
                header?: never;
                path: {
                    channel_id: components["schemas"]["Uuid"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PostChannelMessageRequest"];
                };
            };
            responses: {
                /** @description Message posted */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Message"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/messages/{message_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                message_id: components["schemas"]["Uuid"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a message */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    message_id: components["schemas"]["Uuid"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Message deleted */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        options?: never;
        head?: never;
        /** Edit a message */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    message_id: components["schemas"]["Uuid"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["EditMessageRequest"];
                };
            };
            responses: {
                /** @description Message updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Message"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        trace?: never;
    };
    "/messages/{message_id}/replies": {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                message_id: components["schemas"]["Uuid"];
            };
            cookie?: never;
        };
        /** Get thread replies */
        get: {
            parameters: {
                query?: {
                    limit?: number;
                    offset?: number;
                };
                header?: never;
                path: {
                    message_id: components["schemas"]["Uuid"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of replies */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MessageList"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/direct_messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List DM conversations for the user */
        get: {
            parameters: {
                query: {
                    organization_id: components["schemas"]["Uuid"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of DM conversations */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DirectMessageConversationList"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
            };
        };
        put?: never;
        /** Start a DM conversation */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["StartDmRequest"];
                };
            };
            responses: {
                /** @description DM conversation created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DirectMessageConversation"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                409: components["responses"]["Conflict"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/direct_messages/{conversation_id}/messages": {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                conversation_id: components["schemas"]["Uuid"];
            };
            cookie?: never;
        };
        /** Get DM message history */
        get: {
            parameters: {
                query?: {
                    limit?: number;
                    offset?: number;
                };
                header?: never;
                path: {
                    conversation_id: components["schemas"]["Uuid"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of messages */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MessageList"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        /** Post a message to a DM conversation */
        post: {
            parameters: {
                query?: {
                    limit?: number;
                    offset?: number;
                };
                header?: never;
                path: {
                    conversation_id: components["schemas"]["Uuid"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PostDmMessageRequest"];
                };
            };
            responses: {
                /** @description Message posted */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Message"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List files in an organization */
        get: {
            parameters: {
                query: {
                    organization_id: components["schemas"]["Uuid"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of files */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["FileList"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
            };
        };
        put?: never;
        /** Record metadata for an uploaded file */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RecordUploadRequest"];
                };
            };
            responses: {
                /** @description File recorded */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["FileResponse"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/files/{file_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                file_id: components["schemas"]["Uuid"];
            };
            cookie?: never;
        };
        /** Get file metadata */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    file_id: components["schemas"]["Uuid"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description File metadata */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["File"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/messages/{message_id}/attachments": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                message_id: components["schemas"]["Uuid"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Attach a file to a message */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    message_id: components["schemas"]["Uuid"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AttachFileRequest"];
                };
            };
            responses: {
                /** @description File attached */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/messages/{message_id}/reactions": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                message_id: components["schemas"]["Uuid"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add a reaction to a message */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    message_id: components["schemas"]["Uuid"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AddReactionRequest"];
                };
            };
            responses: {
                /** @description Reaction added */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Reaction"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/messages/{message_id}/reactions/{emoji}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                message_id: components["schemas"]["Uuid"];
                emoji: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove the caller's reaction from a message */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    message_id: components["schemas"]["Uuid"];
                    emoji: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Reaction removed */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/websocket": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Establish an authenticated WebSocket connection
         * @description Upgrades the HTTP connection to a WebSocket and starts delivering
         *     real-time events. The connection is automatically subscribed to all
         *     organizations the authenticated user belongs to. Send and receive
         *     JSON envelopes as described in the WebSocket protocol documentation.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description WebSocket upgrade accepted */
                101: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mcp/v1/sse": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * MCP Server-Sent Events stream
         * @description Opens a long-lived Server-Sent Events stream for server-initiated MCP
         *     messages. Requires the `Mcp-Session-Id` header identifying an existing
         *     session and an `Accept: text/event-stream` header.
         */
        get: {
            parameters: {
                query?: never;
                header: {
                    "Mcp-Session-Id": string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Server-Sent Events stream */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/event-stream": string;
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
                /** @description Accept header must allow text/event-stream */
                406: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        /**
         * MCP Streamable HTTP client-message endpoint
         * @description Accepts JSON-RPC requests for the Model Context Protocol server and
         *     returns responses as a Server-Sent Events stream. A successful
         *     `initialize` request creates a session and returns a `Mcp-Session-Id`
         *     header that must be included on subsequent requests. All requests must
         *     accept both `application/json` and `text/event-stream`.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": Record<string, never>;
                };
            };
            responses: {
                /** @description JSON-RPC response delivered as SSE events */
                200: {
                    headers: {
                        /** @description Session ID for stateful requests (present on initialize) */
                        "Mcp-Session-Id"?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "text/event-stream": string;
                    };
                };
                /** @description Notification accepted (empty body) */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
                /** @description Accept header missing required MIME types */
                406: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Content-Type must be application/json */
                415: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Format: uuid
         * @example 550e8400-e29b-41d4-a716-446655440000
         */
        Uuid: string;
        Error: {
            /**
             * @description Machine-readable error category
             * @example validation
             */
            code: string;
            /** @description Human-readable message */
            error: string;
        };
        /** @enum {string} */
        Role: "owner" | "admin" | "member";
        /** @enum {string} */
        ConversationType: "channel" | "direct_message";
        User: {
            id: components["schemas"]["Uuid"];
            /** Format: email */
            email: string;
            display_name: string;
            password_hash: string;
            avatar_url?: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        UserResponse: {
            id: components["schemas"]["Uuid"];
            /** Format: email */
            email: string;
            display_name: string;
            avatar_url?: string | null;
        };
        Organization: {
            id: components["schemas"]["Uuid"];
            name: string;
            slug: string;
            owner_id: components["schemas"]["Uuid"];
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        OrganizationMembership: {
            user_id: components["schemas"]["Uuid"];
            organization_id: components["schemas"]["Uuid"];
            role: components["schemas"]["Role"];
            /** Format: date-time */
            joined_at: string;
        };
        OrganizationList: {
            items: components["schemas"]["Organization"][];
        };
        Channel: {
            id: components["schemas"]["Uuid"];
            organization_id: components["schemas"]["Uuid"];
            name: string;
            topic?: string | null;
            purpose?: string | null;
            is_private: boolean;
            created_by: components["schemas"]["Uuid"];
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            archived_at?: string | null;
        };
        ChannelList: {
            items: components["schemas"]["Channel"][];
        };
        ChannelMembership: {
            user_id: components["schemas"]["Uuid"];
            channel_id: components["schemas"]["Uuid"];
            /** Format: date-time */
            joined_at: string;
        };
        Message: {
            id: components["schemas"]["Uuid"];
            conversation_id: components["schemas"]["Uuid"];
            conversation_type: components["schemas"]["ConversationType"];
            parent_id?: components["schemas"]["Uuid"];
            author_id: components["schemas"]["Uuid"];
            content: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            /** Format: date-time */
            deleted_at?: string | null;
        };
        MessageList: {
            items: components["schemas"]["Message"][];
        };
        DirectMessageConversation: {
            id: components["schemas"]["Uuid"];
            organization_id: components["schemas"]["Uuid"];
            member_ids: components["schemas"]["Uuid"][];
            /** Format: date-time */
            created_at: string;
        };
        DirectMessageConversationList: {
            items: components["schemas"]["DirectMessageConversation"][];
        };
        File: {
            id: components["schemas"]["Uuid"];
            organization_id: components["schemas"]["Uuid"];
            uploaded_by: components["schemas"]["Uuid"];
            file_name: string;
            mime_type: string;
            /** Format: int64 */
            size_bytes: number;
            storage_path: string;
            thumbnail_path?: string | null;
            /** Format: date-time */
            created_at: string;
        };
        FileResponse: {
            id: components["schemas"]["Uuid"];
            file_name: string;
            mime_type: string;
            /** Format: int64 */
            size_bytes: number;
        };
        FileList: {
            items: components["schemas"]["File"][];
        };
        RegisterRequest: {
            /** Format: email */
            email: string;
            display_name: string;
            password: string;
            organization_name: string;
            organization_slug: string;
        };
        RegisterResponse: {
            user: components["schemas"]["UserResponse"];
            organization: components["schemas"]["Organization"];
        };
        LoginRequest: {
            /** Format: email */
            email: string;
            password: string;
        };
        LoginResponse: {
            token: string;
            user: components["schemas"]["UserResponse"];
        };
        UpdateProfileRequest: {
            display_name?: string;
            avatar_url?: string | null;
        };
        CreateOrganizationRequest: {
            name: string;
            slug: string;
        };
        InviteMemberRequest: {
            /** Format: email */
            email: string;
            role: components["schemas"]["Role"];
        };
        ChangeRoleRequest: {
            user_id: components["schemas"]["Uuid"];
            role: components["schemas"]["Role"];
        };
        CreateChannelRequest: {
            name: string;
            is_private: boolean;
        };
        UpdateChannelRequest: {
            topic?: string | null;
            purpose?: string | null;
        };
        PostChannelMessageRequest: {
            content: string;
            parent_id?: components["schemas"]["Uuid"];
        };
        PostDmMessageRequest: {
            content: string;
            parent_id?: components["schemas"]["Uuid"];
        };
        EditMessageRequest: {
            content: string;
        };
        StartDmRequest: {
            organization_id: components["schemas"]["Uuid"];
            member_ids: components["schemas"]["Uuid"][];
        };
        RecordUploadRequest: {
            organization_id: components["schemas"]["Uuid"];
            file_name: string;
            mime_type: string;
            /** Format: int64 */
            size_bytes: number;
            storage_path: string;
        };
        AttachFileRequest: {
            file_id: components["schemas"]["Uuid"];
        };
        Reaction: {
            message_id: components["schemas"]["Uuid"];
            user_id: components["schemas"]["Uuid"];
            emoji: string;
            /** Format: date-time */
            created_at: string;
        };
        AddReactionRequest: {
            emoji: string;
        };
    };
    responses: {
        /** @description Validation error */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Missing or invalid session */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Caller lacks permission */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Resource not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Resource already exists */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
